### ISSUE TITLE
redefinition of 'class ADXL345'

### ISSUE THREAD

**Issue by halil1903** [kennethlimcp/spark-adxl345#1]
Veryfing code using this library in Particle Build fails with this error:
```
ADXL345/ADXL345.h:96:7: error: redefinition of 'class ADXL345'
 class ADXL345
       ^
```

**Comment by kennethlimcp** [comment]
How are you using the library? I have updated some minor fixes and tested working in the Web IDE.

**Comment by halil1903** [comment]
Adxl345.nothing work library so not finish to project
2015-12-12 3:44 GMT+02:00 Kenneth Lim <notifications@github.com>:

**Comment by kennethlimcp** [comment]
Did you wire it up correctly in the first place?

**Comment by halil1903** [comment]
yes but i have using microcontroller card a photon,not arduino.

2015-12-12 16:52 GMT+02:00 Kenneth Lim <notifications@github.com>:
